apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: habit

resources:
  - namespace.yaml
  - api/deployment.yaml
  - api/service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: habitTracker
  app.kubernetes.io/managed-by: homeLabOps

images:
  - name: ghcr.io/keeru-srinivas/habit-api
    newName: ghcr.io/keeru-srinivas/habit-api
    newTag: latest
