apiVersion: v1
kind: Service
metadata:
  name: saral-api
  labels:
    app.kubernetes.io/name: saral-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saral-api
  ports:
    - name: http
      port: 9260
      targetPort: 9260
