apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkitup

resources:
  - namespace.yaml
  - api/deployment.yaml
  - api/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress-api.yaml
  - ingress-ui.yaml

commonLabels:
  app.kubernetes.io/part-of: linkItUp
  app.kubernetes.io/managed-by: homeLabOps

images:
  - name: ghcr.io/uttu28/linkitup-api
    newName: ghcr.io/uttu28/linkitup-api
    newTag: "d7d6b96"
  - name: ghcr.io/uttu28/linkitup-ui
    newName: ghcr.io/uttu28/linkitup-ui
    newTag: "d7d6b96"
