apiVersion: v1
kind: Service
metadata:
  name: saral-ui
  labels:
    app.kubernetes.io/name: saral-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saral-ui
  ports:
    - name: http
      port: 9261
      targetPort: 9261
