apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saral

resources:
  - namespace.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: saralJobViewer
  app.kubernetes.io/managed-by: homeLabOps

images:
  - name: ghcr.io/uttu28/saral-api
    newName: ghcr.io/uttu28/saral-api
    newTag: "src-a5d07c323d9f"
  - name: ghcr.io/uttu28/saral-ui
    newName: ghcr.io/uttu28/saral-ui
    newTag: "src-7121e6cf0b62"
  - name: ghcr.io/uttu28/saral-redis
    newName: ghcr.io/uttu28/saral-redis
    newTag: "src-d2ae4a1dafa0"
