apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saral-job-viewer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/UttU28/homeLabOps.git
    targetRevision: main
    path: apps/saralJobViewer
  destination:
    server: https://kubernetes.default.svc
    namespace: saral
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
