apiVersion: v1
kind: Service
metadata:
  name: apeksha-api
  labels:
    app.kubernetes.io/name: apeksha-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apeksha-api
  ports:
    - name: http
      port: 9201
      targetPort: 9201
